; Droy Language Compiled Output
; Source: examples/hello.droy
; Generated by Droy Compiler v1.0.1

; ModuleID = 'examples/hello.droy'
source_filename = "examples/hello.droy"

; External functions
declare i32 @printf(i8*, ...)
declare i8* @malloc(i64)
declare void @free(i8*)

; Main function placeholder
define i32 @main() {
entry:
  ; Program would be compiled here
  ret i32 0
}
